/* All free solid fontawesome icons -> https://fontawesome.com/icons?d=gallery&s=solid&m=free */

import {
    faAngleDown,
    faAngleRight,
    faArrowLeft,
    faBars,
    faBookOpen,
    faChartArea,
    faChartBar,
    faChartPie,
    faCheckDouble,
    faChevronDown,
    faChevronUp,
    faCircle,
    faColumns,
    faInfinity,
    faProjectDiagram,
    faSearch,
    faSlidersH,
    faTable,
    faTachometerAlt,
    faUser,
    faHome,
    faRadiationAlt
} from "@fortawesome/free-solid-svg-icons";

export const fontAwesomeSolidIcons = {
    faAngleDown,
    faAngleRight,
    faArrowLeft,
    faBars,
    faBookOpen,
    faChartArea,
    faChartBar,
    faChartPie,
    faChevronDown,
    faChevronUp,
    faCircle,
    faColumns,
    faSearch,
    faTable,
    faTachometerAlt,
    faUser,
    faProjectDiagram,
    faCheckDouble,
    faInfinity,
    faSlidersH,
    faHome,
    faRadiationAlt,
};
